// <auto-generated />
using System;
using ActivosFijosDotNetCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ActivosFijosDotNetCore.Migrations
{
    [DbContext(typeof(ActivosFijosDBContext))]
    partial class ActivosFijosDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ActivosFijosDotNetCore.Models.ActivosFijos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DepreciacionAcumulada");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<int>("IdDepartamento");

                    b.Property<string>("IdEstado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int>("IdTipoActivo");

                    b.Property<decimal>("ValorCompra");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipoActivo");

                    b.ToTable("ActivosFijos");
                });

            modelBuilder.Entity("ActivosFijosDotNetCore.Models.CalculoDepreciacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CuentaCompra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("CuentaDepreciacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal>("DepreciacionAcumulada");

                    b.Property<DateTime>("FechaProceso")
                        .HasColumnType("date");

                    b.Property<int>("IdActivoFijo");

                    b.Property<decimal>("MontoDepreciado");

                    b.HasKey("Id");

                    b.HasIndex("IdActivoFijo");

                    b.ToTable("CalculoDepreciacion");
                });

            modelBuilder.Entity("ActivosFijosDotNetCore.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("IdEstado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("ActivosFijosDotNetCore.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<int>("IdDepartamento");

                    b.Property<string>("IdEstado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdEstado");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("ActivosFijosDotNetCore.Models.Estado", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("ActivosFijosDotNetCore.Models.TipoActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CuentaCompra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("CuentaDepreciacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("IdEstado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.ToTable("TipoActivo");
                });

            modelBuilder.Entity("ActivosFijosDotNetCore.Models.ActivosFijos", b =>
                {
                    b.HasOne("ActivosFijosDotNetCore.Models.Departamento", "IdDepartamentoNavigation")
                        .WithMany("ActivosFijos")
                        .HasForeignKey("IdDepartamento")
                        .HasConstraintName("FK_ActivoFijo_Departamento");

                    b.HasOne("ActivosFijosDotNetCore.Models.Estado", "IdEstadoNavigation")
                        .WithMany("ActivosFijos")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_ActivoFijo_Estado");

                    b.HasOne("ActivosFijosDotNetCore.Models.TipoActivo", "IdTipoActivoNavigation")
                        .WithMany("ActivosFijos")
                        .HasForeignKey("IdTipoActivo")
                        .HasConstraintName("FK_ActivoFijo_TipoActivo");
                });

            modelBuilder.Entity("ActivosFijosDotNetCore.Models.CalculoDepreciacion", b =>
                {
                    b.HasOne("ActivosFijosDotNetCore.Models.ActivosFijos", "IdActivoFijoNavigation")
                        .WithMany("CalculoDepreciacion")
                        .HasForeignKey("IdActivoFijo")
                        .HasConstraintName("FK_CalculoDepreciacion_ActivoFijo");
                });

            modelBuilder.Entity("ActivosFijosDotNetCore.Models.Departamento", b =>
                {
                    b.HasOne("ActivosFijosDotNetCore.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Departamento")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Departamento_Estado");
                });

            modelBuilder.Entity("ActivosFijosDotNetCore.Models.Empleado", b =>
                {
                    b.HasOne("ActivosFijosDotNetCore.Models.Departamento", "IdDepartamentoNavigation")
                        .WithMany("Empleado")
                        .HasForeignKey("IdDepartamento")
                        .HasConstraintName("FK_Empleado_Departamento");

                    b.HasOne("ActivosFijosDotNetCore.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Empleado")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Empleado_Estado");
                });

            modelBuilder.Entity("ActivosFijosDotNetCore.Models.TipoActivo", b =>
                {
                    b.HasOne("ActivosFijosDotNetCore.Models.Estado", "IdEstadoNavigation")
                        .WithMany("TipoActivo")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_TipoActivo_Estado");
                });
#pragma warning restore 612, 618
        }
    }
}
